#!/bin/sh

# SPDX-FileCopyrightText: 2021 Jolla Ltd.
# SPDX-FileCopyrightText: 2025 Jolla Mobile Ltd
#
# SPDX-License-Identifier: BSD-3-Clause

portraitCaptureButtonLocation=$(dconf read /apps/jolla-camera/portraitCaptureButtonLocation)
if [[ "$portraitCaptureButtonLocation" == 1 || "$portraitCaptureButtonLocation" == 5 ]]; then
    dconf write /apps/jolla-camera/portraitCaptureButtonLocation 3
fi

landscapeCaptureButtonLocation=$(dconf read /apps/jolla-camera/landscapeCaptureButtonLocation)
if [[ "$landscapeCaptureButtonLocation" == 3 ]]; then
    dconf write /apps/jolla-camera/landscapeCaptureButtonLocation 5
fi
